# Generated by Django 6.0.6 on 2026-06-29 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridmortapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted'), ('USER_ROLE_CHANGED', 'User Role Changed'), ('USER_PASSWORD_CHANGED', 'User Password Changed'), ('TICKET_CREATED', 'Ticket Created'), ('TICKET_UPDATED', 'Ticket Updated'), ('TICKET_DELETED', 'Ticket Deleted'), ('TICKET_ASSIGNED', 'Ticket Assigned'), ('TICKET_ESCALATED', 'Ticket Escalated'), ('TICKET_REOPENED', 'Ticket Reopened'), ('TICKET_RESOLVED', 'Ticket Resolved'), ('TICKET_CLOSED', 'Ticket Closed'), ('SLA_BREACHED', 'SLA Breached'), ('SLA_MARKED_BREACHED', 'SLA Marked Breached'), ('MESSAGE_ADDED', 'Message Added'), ('MESSAGE_EDITED', 'Message Edited'), ('MESSAGE_DELETED', 'Message Deleted'), ('REPORT_GENERATED', 'Report Generated'), ('REPORT_DOWNLOADED', 'Report Downloaded'), ('REPORT_DELETED', 'Report Deleted'), ('INVENTORY_ASSIGNED', 'Inventory Assigned'), ('INVENTORY_RETURNED', 'Inventory Returned'), ('INVENTORY_ADDED', 'Inventory Added'), ('INVENTORY_UPDATED', 'Inventory Updated'), ('INVENTORY_DELETED', 'Inventory Deleted'), ('SYSTEM_ERROR', 'System Error'), ('SYSTEM_WARNING', 'System Warning'), ('SYSTEM_CONFIG_CHANGED', 'System Configuration Changed')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='ticketauditlog',
            name='gridmortapp_ticket__11c536_idx',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_audit_logs', to='gridmortapp.ticket'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='ticketauditlog',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketauditlog',
            name='user',
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='gridmortapp_user_id_72ef37_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='gridmortapp_action_dea974_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ticket', 'created_at'], name='gridmortapp_ticket__06794a_idx'),
        ),
        migrations.DeleteModel(
            name='TicketAuditLog',
        ),
    ]
