# Generated by Django 6.0.6 on 2026-06-30 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridmortapp', '0002_auditlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_notification_at',
            field=models.DateTimeField(blank=True, help_text='Last time a notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='notification_count',
            field=models.IntegerField(default=0, help_text='Number of notifications sent'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='response_reminder_count',
            field=models.IntegerField(default=0, help_text='Number of response reminders sent'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['last_notification_at'], name='gridmortapp_last_no_7804a6_idx'),
        ),
    ]
